on: workflow_dispatch
name: Create ACR
jobs:
  create-acr:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Create ACR
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az acr create --resource-group rg-cloud-native-fabiano-01 --name acrcloudnativecurso --sku Basic
